### ISSUE TITLE
Some shp files can't be read

### ISSUE THREAD

**Issue by m-mohr** [stactools-packages/fws-nwi#2]
Applies to:
- CA
- NV
- ...

Example error:
````
022-10-21 11:35:17,822 Opening /tmp/tmpqk0m4jbz/CA_shapefile_wetlands/CA_Wetlands.shp for conversion
Traceback (most recent call last):
  File "/home/mm/.local/bin/stac", line 8, in <module>
    sys.exit(run_cli())
  File "/home/mm/.local/lib/python3.8/site-packages/stactools/cli/cli.py", line 38, in run_cli
    cli(prog_name="stac")
  File "/home/mm/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/mm/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/mm/.local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mm/.local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mm/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mm/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/mm/.local/lib/python3.8/site-packages/stactools/fws_nwi/commands.py", line 119, in create_item_command
    item = stac.create_item(source, stac_collection, nogeoparquet, noshp, datetime)
  File "/home/mm/.local/lib/python3.8/site-packages/stactools/fws_nwi/stac.py", line 255, in create_item
    assets = parquet.convert(content[t].files, t, target_folder)
  File "/home/mm/.local/lib/python3.8/site-packages/stactools/fws_nwi/parquet.py", line 41, in convert
    assets[key] = create_asset(file, content_type, dest_folder)
  File "/home/mm/.local/lib/python3.8/site-packages/stactools/fws_nwi/parquet.py", line 98, in create_asset
    for row in reader:
  File "/home/mm/.local/lib/python3.8/site-packages/shapefile.py", line 1168, in __iter__
    for shaperec in self.iterShapeRecords():
  File "/home/mm/.local/lib/python3.8/site-packages/shapefile.py", line 1771, in iterShapeRecords
    for shape, record in izip(self.iterShapes(), self.iterRecords(fields=fields)):
  File "/home/mm/.local/lib/python3.8/site-packages/shapefile.py", line 1483, in iterShapes
    shape = self.__shape(oid=i, bbox=bbox)
  File "/home/mm/.local/lib/python3.8/site-packages/shapefile.py", line 1309, in __shape
    (recNum, recLength) = unpack(">2i", f.read(8))
struct.error: unpack requires a buffer of 8 bytes
````

**Comment by m-mohr** [comment]
The pyshp issue tracker doesn't really help except that it might be an issue with reaching the end of the file too soon. So if e.g. the number fo records in metadata is higher than the actual number. We could try to catch this, but it might lead to incomplete files...

**Comment by m-mohr** [comment]
It indeed seems that the files are reporting wrong numbers. 

- CA_Wetlands.shp reports 354.074 rows in the metadata but in QGIS only 354.046 rows are shown.
- NV_Wetlands.shp reports 254.711 rows in the metadata but in QGIS only 254.403 rows are shown.

**Comment by m-mohr** [comment]
Should be "fixed" in https://github.com/stactools-packages/fws-nwi/commit/3933a319625238327fc69f7dcc50b76c13727c3a @gadomski - Thoughts?

**Comment by m-mohr** [comment]
Update table:count properly

**Comment by gadomski** [comment]
Makes sense to me.
