### ISSUE TITLE
Charset issue for PacTrust and PRVI (Acute Accent)

### ISSUE THREAD

**Issue by m-mohr** [stactools-packages/fws-nwi#6]
`\xb4` is the Acute Accent: https://www.codetable.net/hex/b4

## PacTrust

```
2022-10-21 13:13:01,261 Loading lineage information from /tmp/tmpy3beaw8v/PacTrust_shapefile_wetlands/PacTrust_Wetlands_Project_Metadata.shp
Traceback (most recent call last):
  File "/home/mm/.local/lib/python3.8/site-packages/dateutil/parser/isoparser.py", line 32, in func
    str_in = str_in.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\xb4' in position 18: ordinal not in range(128)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mm/.local/bin/stac", line 8, in <module>
    sys.exit(run_cli())
  File "/home/mm/.local/lib/python3.8/site-packages/stactools/cli/cli.py", line 38, in run_cli
    cli(prog_name="stac")
  File "/home/mm/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/mm/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/mm/.local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mm/.local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mm/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mm/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/mm/.local/lib/python3.8/site-packages/stactools/fws_nwi/commands.py", line 119, in create_item_command
    item = stac.create_item(source, stac_collection, nogeoparquet, noshp, datetime)
  File "/home/mm/.local/lib/python3.8/site-packages/stactools/fws_nwi/stac.py", line 223, in create_item
    item_datetime = isoparse(item_datetime_str)
  File "/home/mm/.local/lib/python3.8/site-packages/dateutil/parser/isoparser.py", line 35, in func
    six.raise_from(ValueError(msg), e)
  File "<string>", line 3, in raise_from
ValueError: ISO-8601 strings should contain only ASCII characters
```

## PRVI

```
2022-10-21 13:14:37,115 Loading lineage information from /tmp/tmphsctsoyw/PRVI_shapefile_wetlands/PRVI_Wetlands_Project_Metadata.shp
Traceback (most recent call last):
  File "/home/mm/.local/lib/python3.8/site-packages/dateutil/parser/isoparser.py", line 32, in func
    str_in = str_in.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\xb4' in position 18: ordinal not in range(128)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mm/.local/bin/stac", line 8, in <module>
    sys.exit(run_cli())
  File "/home/mm/.local/lib/python3.8/site-packages/stactools/cli/cli.py", line 38, in run_cli
    cli(prog_name="stac")
  File "/home/mm/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/mm/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/mm/.local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mm/.local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mm/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mm/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/mm/.local/lib/python3.8/site-packages/stactools/fws_nwi/commands.py", line 119, in create_item_command
    item = stac.create_item(source, stac_collection, nogeoparquet, noshp, datetime)
  File "/home/mm/.local/lib/python3.8/site-packages/stactools/fws_nwi/stac.py", line 223, in create_item
    item_datetime = isoparse(item_datetime_str)
  File "/home/mm/.local/lib/python3.8/site-packages/dateutil/parser/isoparser.py", line 35, in func
    six.raise_from(ValueError(msg), e)
  File "<string>", line 3, in raise_from
ValueError: ISO-8601 strings should contain only ASCII characters
```

**Comment by m-mohr** [comment]
Actually an issue on my side...
